name: Scrape data

on:
  push:
    branches:
      - master
  schedule:
    # Customize to whatever interval you need:
    # https://crontab.guru/every-night-at-midnight
    - cron:  '0 * * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run scrape
    - run: |
        git config user.name gurmanbh
        git config user.email gurmabh@gmail.com
        git add .
        git commit --allow-empty -m "Database updated"
        git push origin master