name: Scrape data

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run scrape
    - run: |
        git config user.name gurmanbh
        git config user.email gurmabh@gmail.com
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin master
